### ISSUE TITLE
What on earth is this? Is there actually a book here?

### ISSUE THREAD

**Issue by Mrodent** [dwyl/book#90]
Just stumbled on this and downloaded the zip. 

There is nothing there.

In answer to another poster in this Issue strand you say we are "rewriting" the book.

OK, here goes: can I find a copy of the previous latest version of the book? Just to find out whether it is any good, or whether I am wasting my time.

Weird.

**Comment by nelsonic** [comment]
@Mrodent we _are_ re-writing the book in a series of chapters.
Have you seen: https://github.com/dwyl/todo-list-javascript-tutorial ?
That's 80 pages of TDD tutorial.

**Comment by nelsonic** [comment]
Please see: https://dwyl.github.io/book for the first 40 pages. :shipit: 
I'm trying to write 500-2000 words (1-2 pages) per day ✍️ 
so this will eventually be a few hundred pages 💯 
and will become our `handbook` for the company & community. 📘 

Thanks again for opening this issue to remind me I was slacking off. 🤦‍♂️ 
<img width="920" alt="image" src="https://user-images.githubusercontent.com/194400/224048735-f27c21f8-0443-4442-84b9-1db5a64bb36f.png">

I will try harder. I promise. 👌
